cache: "./cache"
rss_dir: "./public/rss"
csv_dir: "./public/csv/"
html_dir: "./public"
csv_file: "./album_of_the_day.csv"
backup_csv_file: "./random_album_of_the_day.csv"
songlink_api: "https://api.song.link/v1-alpha.1/links"
url_parameters: 
  userCountry: "FR"